### ISSUE TITLE
SOAPAction Header

### ISSUE THREAD

**Issue by conradkdotcom** [ideaconnect/idct-soap-client#8]
Hello again !

I struggled to understand why my SOAP requests were failing with this client: it was because I hadn't added the SOAPAction header.

Maybe it would be wise to add an example in the README, that says that "SOAPAction" is probably required ?

It seems like not all webservices require this header. But some do and will fail if it is not present.

Regards,
Conrad

**Comment by ideaconnect** [comment]
Thanks for sharing! 
Will just try to add it :)

I guess although it may be often not required (as never experienced a need) it seems according to soap definition it should be there.

Sorry for the issue, will try to fix it.

**Comment by staabm** [comment]
We also use services which require this header.

**Comment by ideaconnect** [comment]
Created a Pull Request for that:
https://github.com/ideaconnect/idct-soap-client/pull/9
